AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'

Documentation:
  Enabled: false
MethodLength:
  Exclude:
    - 'db/migrate/**/*'

require:
#  - rubocop-rspec_rails
  - rubocop-rails


Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/HashIndentation:
  EnforcedStyle: key