AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'doc/**/*'
    - 'coverage/**/*'

Documentation:
  Enabled: false
MethodLength:
  Exclude:
    - 'db/migrate/**/*'

require:
#  - rubocop-rspec_rails
  - rubocop-rails

inherit_gem:
  rubocop-rails_config: config/rails.yml

Layout/IndentationWidth:
  Width: 2

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods