default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: project_development

test:
  <<: *default
  database: project_test

ci_test:
  adapter: postgresql
  host: postgres
  database: ci_test
  username: runner
  password: runner
